n = 8;  % number of subgroups 
params.VE = zeros(n,4); %[0, 0.4, 0.56, 0.802] .* ones(n,4);
params.kappa  = 0.7 * ones(n,4);
params.p      = [0.3, 0.4, 0.5, 0.7] .* ones(n,4);
params.omega  = 1/3 * ones(n,4);
params.omegap = 1/5 * ones(n,4);
params.omegapp = 1/5 * ones(n,4);
params.gamma  = 1/5 * ones(n,4);
params.gammap = 1/10 * ones(n,4);
params.gammapp = 0 * ones(n,4);
params.mu = 0 * ones(n,4);
params.f      = 0 * ones(n,4);
params.br     = 0 * ones(n,4);
params.dr     = 0 * ones(n,4);  

kappa = params.kappa;
p = params.p;
omega = params.omega;
omegap = params.omegap;
omegapp = params.omegapp;
gamma = params.gamma;
gammap = params.gammap;
gammapp = params.gammapp;
mu = params.mu;
f = params.f;
br = params.br;
dr = params.dr;
kappa = params.kappa;
p = params.p;